import numpy as np
import tensorflow as tf
from ncps.wirings import NCP
from .base_wiring import BaseWiring


class SparseLinear(tf.keras.layers.Layer):
    """Dense layer with a fixed binary connectivity mask.

    The mask determines which connections exist. Weights at masked-off
    positions are zeroed each forward pass (W * mask), so gradients there
    are also zero — the sparsity is permanent throughout training.

    Args:
        units:  output dimension
        mask:   numpy bool/int array of shape (input_dim, units), 1 = connected
    """

    def __init__(self, units, mask, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self._mask_np = np.array(mask, dtype=np.float32)

    def build(self, input_shape):
        self.W = self.add_weight(
            name='W', shape=(input_shape[-1], self.units),
            dtype=tf.float32, initializer='glorot_uniform',
        )
        self.mask = tf.constant(self._mask_np, dtype=tf.float32)
        self.built = True

    def call(self, x):
        return x @ (self.W * self.mask)


class NCPWiring(BaseWiring):
    """Three stacked RNN layers (inter -> command -> motor) with sparse
    inter-layer connections generated by NCP wiring.

    Connections within each layer are dense (standard RNN recurrent weights).
    Connections *between* layers are sparse: a SparseLinear layer with a
    binary mask derived from the NCP adjacency matrix sits between each
    pair of RNN layers.

    Note: The ncps.wirings.NCP class uses neuron ordering [motor | command | inter]
    internally, so neuron index lists are extracted via w._inter_neurons,
    w._command_neurons, w._motor_neurons before computing masks.

    Args:
        cell_cls:         BaseCell subclass (e.g. LRC_Cell, LSTM_Cell)
        inter_neurons:    number of inter neurons
        command_neurons:  number of command neurons
        motor_neurons:    number of motor neurons (= model output size)
        seed:             random seed for NCP wiring generation (default 42)
        **cell_kwargs:    forwarded to each cell constructor
    """

    def __init__(self, cell_cls, inter_neurons, command_neurons, motor_neurons,
                 seed=42, **cell_kwargs):
        super().__init__(cell=None)
        self.cell_cls = cell_cls
        self.inter_neurons = inter_neurons
        self.command_neurons = command_neurons
        self.motor_neurons = motor_neurons
        self.seed = seed
        self.cell_kwargs = cell_kwargs

        # Build NCP wiring to get sparse inter-layer connectivity masks.
        # ncps.wirings.NCP uses ordering [motor | command | inter] internally.
        # We extract actual neuron index lists from private attributes.
        wiring = NCP(
            inter_neurons=inter_neurons,
            command_neurons=command_neurons,
            motor_neurons=motor_neurons,
            sensory_fanout=max(1, inter_neurons // 2),
            inter_fanout=max(1, command_neurons // 2),
            recurrent_command_synapses=max(1, command_neurons // 2),
            motor_fanin=max(1, command_neurons // 2),
            seed=seed,
        )
        wiring.build(input_shape=0)
        A = wiring.adjacency_matrix

        inter_idx = wiring._inter_neurons    # list of inter neuron indices
        cmd_idx = wiring._command_neurons    # list of command neuron indices
        mot_idx = wiring._motor_neurons      # list of motor neuron indices

        # Extract inter->command and command->motor connectivity masks.
        # A[src, dst] != 0 means a connection from src to dst exists.
        self._inter_to_command = (
            A[np.ix_(inter_idx, cmd_idx)] != 0
        ).astype(np.float32)   # shape: (inter_neurons, command_neurons)

        self._command_to_motor = (
            A[np.ix_(cmd_idx, mot_idx)] != 0
        ).astype(np.float32)   # shape: (command_neurons, motor_neurons)

        assert self._inter_to_command.any(), (
            "NCPWiring: inter→command mask is all-zeros (disconnected layer). "
            "Increase inter_neurons or command_neurons."
        )
        assert self._command_to_motor.any(), (
            "NCPWiring: command→motor mask is all-zeros (disconnected layer). "
            "Increase command_neurons or motor_neurons."
        )

    def build_model(self) -> tf.keras.Sequential:
        return tf.keras.Sequential([
            tf.keras.layers.RNN(
                self.cell_cls(units=self.inter_neurons, **self.cell_kwargs),
                return_sequences=True,
            ),
            SparseLinear(self.command_neurons, self._inter_to_command),
            tf.keras.layers.RNN(
                self.cell_cls(units=self.command_neurons, **self.cell_kwargs),
                return_sequences=True,
            ),
            SparseLinear(self.motor_neurons, self._command_to_motor),
            tf.keras.layers.RNN(
                self.cell_cls(units=self.motor_neurons, **self.cell_kwargs),
                return_sequences=True,
            ),
        ])
